/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ibfocus;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.Timer;

/**
 *
 * @author dzakwanfarabi
 */
public class TS extends javax.swing.JPanel {

    
    String answer;
    private IBFocus biVoc; // Reference to the main frame
    
    // Existing constructor...
    public void setMainFrame(IBFocus mainFrame) {
        this.biVoc = mainFrame;
    }
    
    public TS(String clar) {
        initComponents();
        verSET();
        answer = loadMap("/Users/dzakwanfarabi/.IB-Focus/v1dat.txt");
        System.out.println(clar + " ini clar");
        if(clar.equals("true")){
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibfocus/res/BiFoc-Crescendo_TS.png")));
        }
        load.setVisible(false);
    }
    
    public void setMap(String path, String text){
        try {
            FileOutputStream fos = new FileOutputStream(path);
            String data1 = text;
            byte[] bytes = data1.getBytes();
            fos.write(bytes);
            fos.close();
            System.out.println("Data written to file.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public String loadMap(String path){
        String ans = "Failed to fetch data.";
        try{
            //InputStream is = getClass().getResourceAsStream(path);
            InputStream is = new FileInputStream(path);
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            ans = br.readLine();
            System.out.println(ans);
            br.close();     
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
        return ans;
    }
    public void verSET(){
        String ver = loadMap("/Users/dzakwanfarabi/.IB-Focus/ver.txt");
        verLabel.setText(ver);
        
        System.out.println(ver);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verLabel = new javax.swing.JLabel();
        passField = new ibfocus.PasswordField();
        load = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1450, 820));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        verLabel.setForeground(new java.awt.Color(255, 255, 255));
        verLabel.setText("v2.110");
        add(verLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 730, -1, -1));

        passField.setBackground(new java.awt.Color(0, 0, 0));
        passField.setForeground(new java.awt.Color(255, 255, 255));
        passField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        passField.setLabelText("Access Key");
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFieldKeyReleased(evt);
            }
        });
        add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 140, 50));

        load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibfocus/res/load.gif"))); // NOI18N
        add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 500, 280));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibfocus/res/BiFoc-updatedsize.png"))); // NOI18N
        add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1470, 940));
    }// </editor-fold>//GEN-END:initComponents

    private void passFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyReleased
        String passText = new String(passField.getPassword());
        if (passText.equals(answer)){
            passField.setVisible(false);
            load.setVisible(true);
            Timer jedacuy = new Timer(7500, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setMap("/Users/dzakwanfarabi/.IB-Focus/ib-login.txt", "true");
                    biVoc.dispose();
                    new MainFrame().setVisible(true);
                }
            });
            jedacuy.setRepeats(false);
            jedacuy.start();
        }
    }//GEN-LAST:event_passFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel load;
    private ibfocus.PasswordField passField;
    private javax.swing.JLabel verLabel;
    // End of variables declaration//GEN-END:variables
}
